name: "Docker Push"
description: "build, tag and pushes the container"
author: "Jungyoul Yu <@nalbam>"

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://opspresso/action-docker:v0.5.0

outputs:
  TAG_NAME:
    description: "Your Docker Tag name."
