name: "Docker Push"
description: "build, tag and pushes the container"
author: "Jungyoul Yu <@nalbam>"

branding:
  icon: "anchor"
  color: "blue"

runs:
  using: docker
  image: docker://opspresso/action-docker:v0.2.8
  args:
    - ${{ inputs.registry-type }}

inputs:
  registry-type:
    description: "Your Docker Registry Type."
    required: false
    default: "--docker"
  # USERNAME:
  #   description: 'Your Docker Hub Username.'
  #   required: true
  # PASSWORD:
  #   description: 'Your Docker Hub Password.'
  #   required: true
  # REGISTRY:
  #   description: 'Your Docker Registry Uri.'
  #   required: false
  #   default: 'World'
  # BUILD_PATH:
  #   description: 'The path where the Dockerfile.'
  #   required: false
  #   default: '.'

outputs:
  TAG_NAME:
    description: "Your Docker Tag name."
